"""Gate 1 / Canonicalization tests: perspective transforms, round trips."""

from __future__ import annotations

import chess

from env.action_space import ActionCodec
from env.symmetry import (
    canonicalize,
    map_move_to_original,
    uncanonicalize,
)

FENS = [
    chess.STARTING_FEN,
    "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
    "r1bqkbnr/pppp1ppp/2n5/8/4p1P1/2N2N2/PPPPPP1P/R1BQKB1R b KQkq g3 0 3",
    "r3k2r/8/8/8/8/8/8/R3K2R b KQkq - 0 1",
    "8/4P3/8/8/8/8/8/4K2k w - - 0 1",
    "8/8/8/3k4/8/8/4p3/4K3 b - - 0 1",
    "4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1",
    "4k3/8/8/8/3Pp3/8/8/4K3 b - d3 0 1",
    "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
]


def test_canonical_has_white_to_move():
    for fen in FENS:
        board = chess.Board(fen)
        canon = canonicalize(board)
        assert canon.turn == chess.WHITE


def test_white_to_move_is_identity():
    board = chess.Board(chess.STARTING_FEN)
    canon = canonicalize(board)
    assert canon.fen() == board.fen()
    assert map_move_to_original(chess.Move.from_uci("e2e4"), chess.WHITE) == (
        chess.Move.from_uci("e2e4")
    )


def test_black_to_move_flips_and_swaps():
    # After 1.e4 (black to move), canonical black pawn (originally the white
    # e-pawn) sits on e5, and white-to-move canonical side owns the back rank.
    board = chess.Board("rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1")
    canon = canonicalize(board)
    assert canon.piece_at(chess.E5) == chess.Piece(chess.PAWN, chess.BLACK)
    assert canon.piece_at(chess.E1) == chess.Piece(chess.KING, chess.WHITE)
    assert canon.fen() == (
        "rnbqkbnr/pppp1ppp/8/4p3/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
    )


def test_black_castling_rights_map_consistently():
    board = chess.Board("r3k2r/8/8/8/8/8/8/R3K2R b KQkq - 0 1")
    canon = canonicalize(board)
    assert canon.castling_rights == chess.BB_H1 | chess.BB_A1 | chess.BB_H8 | chess.BB_A8
    # The canonical white king should have both castling rights.
    assert bool(canon.castling_rights & chess.BB_H1)
    assert bool(canon.castling_rights & chess.BB_A1)


def test_en_passant_square_maps_correctly():
    board = chess.Board("4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1")  # white to move, EP d6
    canon = canonicalize(board)
    assert canon.turn == chess.WHITE
    assert canon.ep_square == chess.D6
    # Black to move with EP square d3 -> canonical d6.
    board2 = chess.Board("4k3/8/8/8/3Pp3/8/8/4K3 b - d3 0 1")
    canon2 = canonicalize(board2)
    assert canon2.ep_square == chess.D6


def test_move_mapping_black_to_white():
    # Canonical white advance e2-e4 equals original black advance e7-e5.
    board = chess.Board("rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1")
    canon = canonicalize(board)
    move = map_move_to_original(chess.Move.from_uci("e2e4"), chess.BLACK)
    assert move == chess.Move.from_uci("e7e5")
    assert move in board.legal_moves
    _ = canon


def test_round_trip_preserves_legal_moves():
    """MANDATORY TEST: original -> canonical -> legal canonical actions ->
    decode -> map back preserves the original legal moves exactly."""
    for fen in FENS:
        board = chess.Board(fen)
        orig_turn = board.turn
        canon = canonicalize(board)

        original_set = {m.uci() for m in board.legal_moves}
        round_trip = set()
        for action in ActionCodec.encode_legal_moves(canon):
            canonical_move = ActionCodec.decode(action)
            mapped = map_move_to_original(canonical_move, orig_turn)
            assert mapped in board.legal_moves, (
                f"{fen}: {canonical_move.uci()} mapped to {mapped.uci()} illegally"
            )
            round_trip.add(mapped.uci())

        assert round_trip == original_set, (
            f"{fen}: round trip mismatch\n  got   {sorted(round_trip)}\n  want  {sorted(original_set)}"
        )


def test_uncanonicalize_restores_original():
    for fen in FENS:
        board = chess.Board(fen)
        canon = canonicalize(board)
        restored = uncanonicalize(canon, board.turn)
        assert restored.fen() == board.fen()


def test_mate_position_canonicalization():
    # Fool's mate, generated by move replay so the mate is guaranteed.
    b = chess.Board()
    for move in ("f3", "e5", "g4", "Qh4"):
        b.push_san(move)
    assert b.is_checkmate()
    canon = canonicalize(b)
    assert canon.is_checkmate()